.\" Manpage for VIM.
.TH man 1 "2021" "1.0" "VIM"
.SH DELETE
[\fIx]dd - \fBDelete x number of lines
.SH UNDO/REDO
[\fIx\fR]u - \fBUndo x changes
.PP
[\fIx\fR]C-r - \fBRedo x changes
.SH YANK
[\fIx\fR]y - \fBYank x lines
.SH SPLIT VERTICALY
:vs [\fIfilename\fR]
.SH SET VARIABLES
:set paste \- \f[B]Fix indentations when pasting via os clipboard

.SH SEE ALSO
ktz.bash(1), ktz.tar(1), ktz.tmux(1), ktz.wsl(1)
.SH AUTHOR
Konrad Ziarko