.\" Manpage for TMUX.
.TH man 1 "2021" "1.0" "TMUX"
.SH Fullscreen current pane
prefix z
.SH Tmux-resurrect - Save environment
prefix C-s
.SH Tmux-resurrect - Load environment
prefix C-r
.SH TMUX-VIM copy
prefix+[, space, enter, prefix+]

.SH SEE ALSO
ktz.bash(1), ktz.tar(1), ktz.vim(1), ktz.wsl(1)
.SH AUTHOR
Konrad Ziarko