.\" Manpage for TAR.
.TH man 1 "2021" "1.0" "TAR"
.SH EXTRACT
tar -zxvf yourfile.tar.gz               - Extract the file to the current directory
.br
tar -C /myfolder -zxvf yourfile.tar.gz  - Extract to specific directory
.br
\fBTo extract .tar file just drop -z flag

.SH SEE ALSO
ktz.bash(1), ktz.tmux(1), ktz.vim(1), ktz.wsl(1)
.SH AUTHOR
Konrad Ziarko